### PR TITLE
#610 fix edit errors

### LINKED ISSUE #610: Projects - Clicking Edit Throws a TypeError
## Overview

In production, clicking edit on the Project Details page or on the Work Package details page will cause the screen to go blank white because it throws an error.

Project Edit:
Screen Shot 2022-04-16 at 6 07 11 PM
Screen Shot 2022-04-16 at 6 08 03 PM

Work Package:
Screen Shot 2022-04-16 at 6 08 24 PM
Screen Shot 2022-04-16 at 6 08 40 PM

### PR DESCRIPTION
**Pull request by jamescd18**
## Changes

Add checks for undefined user set as current project manager / project lead for project / work package. Add emDash to represent undefined user. For work packages, gutted out state storing user names and looking up IDs, replaced with storing IDs directly.

## Notes

n/a

## Test Cases

- too lazy, mvp time

## Screenshots (if applicable)

- too lazy, mvp time

## To Do

_Any remaining things that need to get done_

idk, n/a for now

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://github.com/Northeastern-Electric-Racing/PM-Dashboard-v2/blob/main/docs/ContributorGuide.md) and reach out to your squad if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors
- [x] No newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (if applicable)
- [x] Remove any not-applicable sections
- [x] Assign the PR to yourself
- [x] PR is linked to the ticket
- [x] No `package-lock.json` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack

Closes #610

### CODE REVIEW

File: src/components/projects/wbs-details/work-package-container/work-package-container-view/work-package-edit-details/work-package-edit-details.tsx [hunk 1]
```diff
@@ -106,33 +112,34 @@ const WorkPackageEditDetails: React.FC<Props> = ({ workPackage, users, setters }
...
+          as="select"
+          data-testid={title}
+          onChange={(e) => updateUser(parseInt(e.target.value))}
+        >
+          {defaultUser === undefined ? (
+            <option key={-1} value={-1}>
+              {emDashPipe('')}
+            </option>
+          ) : (
+            <option key={defaultUser.userId} value={defaultUser.userId}>
```
Comment (anthonybernardi) [inline src/components/projects/wbs-details/work-package-container/work-package-container-view/work-package-edit-details/work-package-edit-details.tsx:137]: the value here has to be the same time of value it was before becuase Justin is using different states than I was

File: src/components/projects/wbs-details/work-package-container/work-package-container-view/work-package-edit-details/work-package-edit-details.tsx [hunk 2]
```diff
@@ -106,33 +112,34 @@ const WorkPackageEditDetails: React.FC<Props> = ({ workPackage, users, setters }
...
+              {fullNamePipe(defaultUser)}
+            </option>
+          )}
+          {otherUsers.map((user) => (
+            <option key={user.userId} value={user.userId}>
```
Comment (anthonybernardi) [inline src/components/projects/wbs-details/work-package-container/work-package-container-view/work-package-edit-details/work-package-edit-details.tsx:142]: same thing with the values

**Review by anthonybernardi — CHANGES_REQUESTED** [review]

**Review by anthonybernardi — APPROVED** [review]

**Review by anthonybernardi — APPROVED** [review]
