### PR TITLE
#406 - Logout Button Not Working

### LINKED ISSUE #406: General - Logout Button Not Working
### Browser(s)

Chrome

### Platform(s)

Desktop

### Version(s)

other (specify below)

### Observed Behavior

When the logout white space around the logout button is clicked, nothing happens. The space around the "Logout" label does not trigger the button and log the user out.

### Expected Behavior

The logout button should log you out of the application and take you back to the login screen when clicked.

### Steps to Reproduce

1. Login to the application
2. Navigate to the Logout Button
3. Try to click the whitespace around the logout button

### Proposed Solution

Adjust the white space so that the click target covers more of the whole area, so that users are able to logout by clicking anywhere on the logout button. 

### Screenshots (as needed)

Menu item target area. Lots of this area is clickable but won't trigger the log out function.
Screen Shot 2022-02-14 at 1 22 55 AM

When the mouse hovers on the text itself the color changes and this text is the area that when clicked actually triggers the log out function.
Screen Shot 2022-02-14 at 1 23 10 AM

Video screen recording
https://user-images.githubusercontent.com/51571627/153811441-16ab1343-2b2a-4d80-b3e6-244f824f6628.mov

### PR DESCRIPTION
**Pull request by Ari-S-123**
## Changes

The styling for the settings and logout button should be the same in practice now, their onClick area too should be the same.

## Screenshots (if applicable)

Screenshot 2022-07-13 202830

Screenshot 2022-07-13 202848

Screenshot 2022-07-13 202900

**FINAL:**
Screenshot 2022-07-16 082620

## To Do

_Any remaining things that need to get done_

- [x] Fix Alignment and Spacing of text in Nav User Menu items.

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://github.com/Northeastern-Electric-Racing/PM-Dashboard-v2/blob/main/docs/ContributorGuide.md) and reach out to your squad if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors
- [x] No newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (if applicable)
- [x] Remove any not-applicable sections
- [x] Assign the PR to yourself
- [x] PR is linked to the ticket
- [x] No `package-lock.json` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack

Closes #406

### CODE REVIEW

**Comment by jamescd18** [comment]
Looks fine to me

File: src/frontend/layouts/nav-top-bar/nav-user-menu/nav-user-menu.tsx [hunk 1]
```diff
@@ -39,13 +39,9 @@ const NavUserMenu: React.FC = () => {
             history.push(routes.HOME);
           }}
           render={(renderProps) => (
-            <button
-              className={'nav-link p-0 m-0 ' + styles.logoutButton}
-              onClick={renderProps.onClick}
-              disabled={renderProps.disabled}
```
Comment (jamescd18) [inline src/frontend/layouts/nav-top-bar/nav-user-menu/nav-user-menu.tsx:45]: Is this functionality being lost? Technically it is used sorta ish.

File: src/frontend/layouts/nav-top-bar/nav-user-menu/nav-user-menu.tsx [hunk 2]
```diff
@@ -39,13 +39,9 @@ const NavUserMenu: React.FC = () => {
...
-            >
+            <div className={'nav-link ' + styles.dropdownItems} onClick={renderProps.onClick}>
```
Comment (jamescd18) [inline src/frontend/layouts/nav-top-bar/nav-user-menu/nav-user-menu.tsx:42]: Role = button for accessibility pls?

File: src/frontend/layouts/nav-top-bar/nav-user-menu/nav-user-menu.tsx [hunk 3]
```diff
@@ -25,12 +25,12 @@ const NavUserMenu: React.FC = () => {
     >
       <NavDropdown.ItemText>Logged in as: {auth.user?.emailId}</NavDropdown.ItemText>
       <NavDropdown.Divider />
-      <NavDropdown.Item as="div">
-        <Link className="nav-link p-0" role="button" to="/settings">
+      <NavDropdown.Item className={styles.UserMenuItem}>
+        <Link className={'nav-link ' + styles.dropdownItems} role="button" to="/settings">
```
Comment (jamescd18) [inline src/frontend/layouts/nav-top-bar/nav-user-menu/nav-user-menu.tsx:29]: Can you replace hardcores string while we're here fixing it?

**Review by jamescd18 — CHANGES_REQUESTED** [review]
Looks great, minor tweaks

**Review by jamescd18 — APPROVED** [review]
